import type {
  PetFollowUpItem,
  PetFollowUpMutationPayload,
  PetRegisteredFollowUp,
  PetRegisteredFollowUpItem,
  RegisterPetFollowUpInput,
} from "@cjhyy/code-shell-pet";
import { sessionSelectorId } from "@cjhyy/code-shell-pet/disclosure";
import { petFollowUpStateId } from "../../shared/pet-work-item-id.js";
import type { DesktopPetSession } from "./pet-state-aggregator.js";
import { petFollowUpId } from "./pet-follow-up-id.js";
import { mapWithConcurrency } from "./map-with-concurrency.js";
import type { PetSummaryService } from "./pet-summary-service.js";
import type { PetSummaryStore } from "./pet-summary-store.js";
import type { PetWorkInboxSnapshot } from "./pet-work-inbox-store.js";
import type { PetRegisteredFollowUpStore } from "./pet-registered-follow-up-store.js";

const MAX_VISIBLE_FOLLOW_UPS = 20;
const MAX_TRACKED_FOLLOW_UPS = 100;
const MAX_NEW_GENERATIONS = 20;
const GENERATION_CONCURRENCY = 5;

export interface PetDerivedFollowUpSummaryRow {
  kind: "derived-session";
  followUpId: string;
  sessionId: string;
  title: string;
  workspace?: string;
  terminalAt: number;
  text: string;
}

export type PetRegisteredFollowUpSummaryRow = Omit<PetRegisteredFollowUpItem, "id"> & {
  followUpId: string;
  sessionId?: string;
};
export type PetFollowUpSummaryRow = PetDerivedFollowUpSummaryRow | PetRegisteredFollowUpSummaryRow;

export interface PetFollowUpMutationResult {
  action: "complete" | "dismiss" | "cancel" | "reschedule";
  followUpId: string;
  title: string;
  revision?: number;
}

export interface PetFollowUpInbox {
  getSnapshot(): PetWorkInboxSnapshot;
  addIfAbsentDurably(id: string): Promise<{ added: boolean; snapshot: PetWorkInboxSnapshot }>;
}

export interface PetFollowUpService {
  /** Canonical feed used by the renderer; includes handled rows for its state filter. */
  collect(): Promise<PetFollowUpSummaryRow[]>;
  /** Canonical open feed injected into Mimi's FollowUps read capability. */
  listOpen(): Promise<PetFollowUpItem[]>;
  /** Register an explicit user obligation; the caller supplies host-authored identity and route. */
  register(input: RegisterPetFollowUpInput): Promise<PetRegisteredFollowUp>;
  /** Exact, durable mutation behind Mimi's ManageFollowUp capability. */
  mutate(
    input: Exclude<PetFollowUpMutationPayload, { action: "register" }>,
  ): Promise<PetFollowUpMutationResult>;
}

/**
 * One canonical feed for result-derived follow-ups and explicitly registered
 * obligations. The former retain their handled-state namespace; the latter
 * have a versioned durable record so UI handling also fences future wakes.
 */
export function createPetFollowUpService(deps: {
  listSessions(): readonly DesktopPetSession[];
  summaryStore: PetSummaryStore;
  summaryService: PetSummaryService;
  inbox: PetFollowUpInbox;
  registered?: PetRegisteredFollowUpStore;
}): PetFollowUpService {
  const rowOf = (
    session: DesktopPetSession,
    terminalAt: number,
    text: string,
  ): PetDerivedFollowUpSummaryRow => ({
    kind: "derived-session",
    followUpId: petFollowUpId(session.agentSessionId, terminalAt),
    sessionId: session.agentSessionId,
    title: session.title ?? session.agentSessionId.slice(-8),
    ...(session.workspaceDisplayName ? { workspace: session.workspaceDisplayName } : {}),
    terminalAt,
    text,
  });

  function registeredRow(row: PetRegisteredFollowUp): PetRegisteredFollowUpSummaryRow {
    const session = row.sourceSessionId
      ? deps.listSessions().find((entry) => entry.agentSessionId === row.sourceSessionId)
      : undefined;
    return {
      kind: "registered",
      followUpId: row.id,
      title: row.title,
      text: row.text,
      revision: row.revision,
      wakeAt: row.wakeAt,
      timezone: row.timezone,
      intent: row.intent,
      missedPolicy: row.missedPolicy,
      catchUpUntil: row.catchUpUntil,
      status: row.status,
      wakeState: row.wake.status,
      createdAt: row.createdAt,
      ...(row.wake.detail ? { wakeDetail: row.wake.detail } : {}),
      ...(row.sourceSessionId
        ? {
            sourceSessionId: row.sourceSessionId,
            sessionId: row.sourceSessionId,
            sessionSelector: sessionSelectorId(row.sourceSessionId),
          }
        : {}),
      ...((row.wake.taskId ?? row.taskId) ? { taskId: row.wake.taskId ?? row.taskId } : {}),
      ...(session?.workspaceDisplayName ? { workspace: session.workspaceDisplayName } : {}),
    };
  }

  async function collect(): Promise<PetFollowUpSummaryRow[]> {
    // A late startup load must never overwrite entries generated by an early
    // workbench or Mimi request.
    await Promise.all([deps.summaryStore.load(), deps.registered?.load()]);
    const completed = deps
      .listSessions()
      .filter((session) => !session.external && session.terminal?.status === "completed")
      .sort((left, right) => right.terminal!.at - left.terminal!.at);

    const cachedRows: PetDerivedFollowUpSummaryRow[] = [];
    const toGenerate: Array<{ session: DesktopPetSession; terminalAt: number }> = [];
    for (const session of completed) {
      const terminalAt = session.terminal!.at;
      const cached = deps.summaryStore.get(session.agentSessionId);
      if (cached && cached.terminalAt === terminalAt) {
        if (cached.text) cachedRows.push(rowOf(session, terminalAt, cached.text));
        continue;
      }
      toGenerate.push({ session, terminalAt });
    }

    const generated = await mapWithConcurrency(
      toGenerate.slice(0, MAX_NEW_GENERATIONS),
      GENERATION_CONCURRENCY,
      async ({ session, terminalAt }) => {
        const summary = await deps.summaryService.summarize(session.agentSessionId, terminalAt);
        return summary ? rowOf(session, terminalAt, summary.text) : null;
      },
    );
    const rows = [
      ...cachedRows,
      ...generated.filter((row): row is PetDerivedFollowUpSummaryRow => row !== null),
    ];
    rows.sort((left, right) => right.terminalAt - left.terminalAt);
    // Registered obligations must not disappear behind a burst of completed Sessions.
    const registered = (deps.registered?.list() ?? []).map(registeredRow);
    return [...registered, ...rows.slice(0, MAX_TRACKED_FOLLOW_UPS)];
  }

  async function listOpen(): Promise<PetFollowUpItem[]> {
    const rows = await collect();
    const handled = new Set(deps.inbox.getSnapshot().dismissedIds);
    return rows
      .filter((row) =>
        row.kind === "registered"
          ? row.status === "open"
          : !handled.has(petFollowUpStateId(row.followUpId)),
      )
      .slice(0, MAX_VISIBLE_FOLLOW_UPS)
      .map((row) => {
        if (row.kind === "registered") {
          const { followUpId, sessionId: _sessionId, ...item } = row;
          return { ...item, id: followUpId };
        }
        return {
          kind: "derived-session" as const,
          id: row.followUpId,
          title: row.title,
          text: row.text,
          terminalAt: row.terminalAt,
          sessionSelector: sessionSelectorId(row.sessionId),
          ...(row.workspace ? { workspace: row.workspace } : {}),
        };
      });
  }

  return {
    collect,
    listOpen,
    async register(input) {
      if (!deps.registered) throw new Error("registered follow-ups are unavailable");
      return deps.registered.register(input);
    },
    async mutate(input) {
      const { action, followUpId } = input;
      if (followUpId.startsWith("registered-followup-")) {
        if (!deps.registered) throw new Error("registered follow-ups are unavailable");
        await deps.registered.load();
        if (input.expectedRevision === undefined)
          throw new Error("registered follow-up requires expectedRevision");
        const row =
          action === "reschedule"
            ? await deps.registered.reschedule(followUpId, input.expectedRevision, input)
            : action === "cancel"
              ? await deps.registered.cancel(followUpId, input.expectedRevision)
              : await deps.registered.handle(followUpId, input.expectedRevision, action);
        return { action, followUpId, title: row.title, revision: row.revision };
      }
      if (
        (action !== "complete" && action !== "dismiss") ||
        !/^followup-[A-Za-z0-9_-]{24}$/u.test(followUpId)
      ) {
        throw new Error("invalid follow-up mutation request");
      }
      const stateId = petFollowUpStateId(followUpId);
      const row = (await collect()).find((candidate) => candidate.followUpId === followUpId);
      // Re-read after the asynchronous collection so a concurrent UI/Mimi
      // mutation cannot make this request report a second successful handling.
      const handled = new Set(deps.inbox.getSnapshot().dismissedIds);
      if (!row || handled.has(stateId)) throw new Error("跟进项不存在或已处理");
      const mutation = await deps.inbox.addIfAbsentDurably(stateId);
      if (!mutation.added) throw new Error("跟进项不存在或已处理");
      return { action, followUpId, title: row.title };
    },
  };
}
