import type { PetFollowUpItem } from "@cjhyy/code-shell-pet";
import { sessionSelectorId } from "@cjhyy/code-shell-pet/disclosure";
import { petFollowUpStateId } from "../../shared/pet-work-item-id.js";
import type { DesktopPetSession } from "./pet-state-aggregator.js";
import { petFollowUpId } from "./pet-follow-up-id.js";
import { mapWithConcurrency } from "./map-with-concurrency.js";
import type { PetSummaryService } from "./pet-summary-service.js";
import type { PetSummaryStore } from "./pet-summary-store.js";
import type { PetWorkInboxSnapshot } from "./pet-work-inbox-store.js";

const MAX_VISIBLE_FOLLOW_UPS = 20;
const MAX_TRACKED_FOLLOW_UPS = 100;
const MAX_NEW_GENERATIONS = 20;
const GENERATION_CONCURRENCY = 5;

export interface PetFollowUpSummaryRow {
  followUpId: string;
  sessionId: string;
  title: string;
  workspace?: string;
  terminalAt: number;
  text: string;
}

export interface PetFollowUpInbox {
  getSnapshot(): PetWorkInboxSnapshot;
  addIfAbsentDurably(id: string): Promise<{ added: boolean; snapshot: PetWorkInboxSnapshot }>;
}

export interface PetFollowUpService {
  /** Canonical feed used by the renderer; includes handled rows for its state filter. */
  collect(): Promise<PetFollowUpSummaryRow[]>;
  /** Canonical open feed injected into Mimi's FollowUps read capability. */
  listOpen(): Promise<PetFollowUpItem[]>;
  /** Exact, durable mutation behind Mimi's ManageFollowUp capability. */
  mutate(input: {
    action: "complete" | "dismiss";
    followUpId: string;
  }): Promise<{ action: "complete" | "dismiss"; followUpId: string; title: string }>;
}

/**
 * Owns the complete Needs-follow-up lifecycle. It intentionally has no Todo
 * API: both the workbench and Mimi consume the same canonical rows and durable
 * handled-state namespace.
 */
export function createPetFollowUpService(deps: {
  listSessions(): readonly DesktopPetSession[];
  summaryStore: PetSummaryStore;
  summaryService: PetSummaryService;
  inbox: PetFollowUpInbox;
}): PetFollowUpService {
  const rowOf = (
    session: DesktopPetSession,
    terminalAt: number,
    text: string,
  ): PetFollowUpSummaryRow => ({
    followUpId: petFollowUpId(session.agentSessionId, terminalAt),
    sessionId: session.agentSessionId,
    title: session.title ?? session.agentSessionId.slice(-8),
    ...(session.workspaceDisplayName ? { workspace: session.workspaceDisplayName } : {}),
    terminalAt,
    text,
  });

  async function collect(): Promise<PetFollowUpSummaryRow[]> {
    // A late startup load must never overwrite entries generated by an early
    // workbench or Mimi request.
    await deps.summaryStore.load();
    const completed = deps
      .listSessions()
      .filter((session) => !session.external && session.terminal?.status === "completed")
      .sort((left, right) => right.terminal!.at - left.terminal!.at);

    const cachedRows: PetFollowUpSummaryRow[] = [];
    const toGenerate: Array<{ session: DesktopPetSession; terminalAt: number }> = [];
    for (const session of completed) {
      const terminalAt = session.terminal!.at;
      const cached = deps.summaryStore.get(session.agentSessionId);
      if (cached && cached.terminalAt === terminalAt) {
        if (cached.text) cachedRows.push(rowOf(session, terminalAt, cached.text));
        continue;
      }
      toGenerate.push({ session, terminalAt });
    }

    const generated = await mapWithConcurrency(
      toGenerate.slice(0, MAX_NEW_GENERATIONS),
      GENERATION_CONCURRENCY,
      async ({ session, terminalAt }) => {
        const summary = await deps.summaryService.summarize(session.agentSessionId, terminalAt);
        return summary ? rowOf(session, terminalAt, summary.text) : null;
      },
    );
    const rows = [
      ...cachedRows,
      ...generated.filter((row): row is PetFollowUpSummaryRow => row !== null),
    ];
    rows.sort((left, right) => right.terminalAt - left.terminalAt);
    return rows.slice(0, MAX_TRACKED_FOLLOW_UPS);
  }

  async function listOpen(): Promise<PetFollowUpItem[]> {
    const rows = await collect();
    const handled = new Set(deps.inbox.getSnapshot().dismissedIds);
    return rows
      .filter((row) => !handled.has(petFollowUpStateId(row.followUpId)))
      .slice(0, MAX_VISIBLE_FOLLOW_UPS)
      .map((row) => ({
        id: row.followUpId,
        title: row.title,
        text: row.text,
        terminalAt: row.terminalAt,
        sessionSelector: sessionSelectorId(row.sessionId),
        ...(row.workspace ? { workspace: row.workspace } : {}),
      }));
  }

  return {
    collect,
    listOpen,
    async mutate({ action, followUpId }) {
      if (
        (action !== "complete" && action !== "dismiss") ||
        !/^followup-[A-Za-z0-9_-]{24}$/u.test(followUpId)
      ) {
        throw new Error("invalid follow-up mutation request");
      }
      const stateId = petFollowUpStateId(followUpId);
      const row = (await collect()).find((candidate) => candidate.followUpId === followUpId);
      // Re-read after the asynchronous collection so a concurrent UI/Mimi
      // mutation cannot make this request report a second successful handling.
      const handled = new Set(deps.inbox.getSnapshot().dismissedIds);
      if (!row || handled.has(stateId)) throw new Error("跟进项不存在或已处理");
      const mutation = await deps.inbox.addIfAbsentDurably(stateId);
      if (!mutation.added) throw new Error("跟进项不存在或已处理");
      return { action, followUpId, title: row.title };
    },
  };
}
