/**
 * Read a persisted engine transcript (~/.code-shell/sessions/<id>/transcript.jsonl)
 * and convert it to an ordered list of FoldItems the renderer can replay
 * through its existing message reducer. Pure parse — no reducer here, so the
 * renderer stays the single source of message-folding logic.
 *
 * TranscriptEvent shape: packages/core/src/types.ts:84-90.
 * StreamEvent shapes:     packages/core/src/types.ts:241-271.
 */
import { sessionsRoot, type ContentBlock } from "@cjhyy/code-shell-core";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import type { FoldItem } from "../preload/types";

interface TranscriptEvent {
  id: string;
  type: string;
  timestamp: number;
  turnNumber: number;
  data: Record<string, unknown>;
}

interface ContentBlockLike {
  type?: string;
  text?: string;
}

type TodoStatus = "pending" | "in_progress" | "completed";
interface TaskInfoLike {
  id: string;
  subject: string;
  activeForm: string;
  status: TodoStatus;
}

/**
 * Convert a TodoWrite tool_use's `args.todos` into the TaskInfo[] the renderer's
 * task_update reducer expects, or null when the args carry no valid todo array.
 * Mirrors core's task.ts (parseTodos → toTaskInfos + the "all items completed ⇒
 * clear the panel" rule) so a disk-rebuilt session restores the SAME panel the
 * live tool would have shown. Kept as a local copy — main can't import core
 * runtime values, only types.
 */
function todosToTasks(args: Record<string, unknown>): TaskInfoLike[] | null {
  const raw = args.todos;
  if (!Array.isArray(raw)) return null;
  const parsed: { content: string; status: TodoStatus; activeForm: string }[] = [];
  for (const r of raw) {
    if (!r || typeof r !== "object") continue;
    const o = r as Record<string, unknown>;
    if (typeof o.content !== "string") continue;
    const status = o.status;
    if (status !== "pending" && status !== "in_progress" && status !== "completed") continue;
    const activeForm = typeof o.activeForm === "string" ? o.activeForm : o.content;
    parsed.push({ content: o.content, status, activeForm });
  }
  const allDone = parsed.length > 0 && parsed.every((t) => t.status === "completed");
  if (allDone) return [];
  return parsed.map((t, i) => ({
    id: String(i + 1),
    subject: t.content,
    activeForm: t.activeForm,
    status: t.status,
  }));
}

function textOf(content: unknown): string {
  if (typeof content === "string") return content;
  if (Array.isArray(content)) {
    return (content as ContentBlockLike[])
      .filter((b) => b && b.type === "text" && typeof b.text === "string")
      .map((b) => b.text as string)
      .join("");
  }
  return "";
}

export function transcriptToFoldItems(jsonl: string): FoldItem[] {
  const items: FoldItem[] = [];
  // Track the last persisted timestamp and whether the LAST turn's content
  // (assistant/tool) arrived AFTER its turn_boundary. In the transcript a
  // `turn_boundary turnNumber=N` marks the START of turn N and is written
  // BEFORE that turn's message/tool events. We translate each boundary to a
  // turn_complete, so the FINAL turn's content (e.g. the closing summary) lands
  // AFTER its turn_complete — which leaves the files_changed card (generated by
  // that turn_complete) stranded BEFORE the summary text ("夹在两段文字中间").
  // We append a closing turn_complete at EOF to re-finalize the last turn so the
  // card moves to the true end. See the post-loop block below.
  let lastTs: number | undefined;
  let sawBoundary = false;
  let pendingContentAfterBoundary = false;
  for (const raw of jsonl.split("\n")) {
    const line = raw.trim();
    if (!line) continue;
    let ev: TranscriptEvent;
    try {
      ev = JSON.parse(line) as TranscriptEvent;
    } catch {
      continue; // skip malformed lines, mirroring core Transcript.loadFromFile
    }
    const d = ev.data ?? {};
    // Real wall-clock the event was persisted at — carried onto each FoldItem so
    // replay can stamp the original createdAt/doneAt (proper "asked at / answered
    // at / elapsed") instead of leaving them blank (which read as 0s elapsed).
    const ts = typeof ev.timestamp === "number" ? ev.timestamp : undefined;
    if (ts !== undefined) lastTs = ts;
    if (ev.type === "turn_boundary") { sawBoundary = true; pendingContentAfterBoundary = false; }
    else if (ev.type === "message" || ev.type === "tool_use") pendingContentAfterBoundary = true;
    switch (ev.type) {
      case "session_meta":
        items.push({
          kind: "stream",
          event: { type: "session_started", sessionId: String(d.sessionId ?? ""), promptTokens: 0 },
          timestamp: ts,
        });
        break;
      case "message": {
        const role = String(d.role ?? "");
        if (role === "user") {
          // Synthetic system-reminder turns (background-job completion
          // notifications) are persisted as `role:user` so the model sees them
          // as a user message, but they are NOT the user's own input. Live they
          // never render as a user bubble — only the assistant's reply shows —
          // so a disk rebuild must drop them too, or the feed sprouts a phantom
          // bubble like "10分钟到了，打开小红书". The engine marks them
          // `injected:true` (steering messages are real user input and are NOT
          // marked, so they correctly survive as bubbles). See engine.ts run().
          if (d.injected === true) break;
          items.push({
            kind: "user",
            text: textOf(d.content),
            ...(d.steerId ? { steerId: String(d.steerId) } : {}),
            ...(d.clientMessageId ? { clientMessageId: String(d.clientMessageId) } : {}),
            timestamp: ts,
          });
        } else if (role === "assistant") {
          items.push({ kind: "stream", event: { type: "stream_request_start", turnNumber: ev.turnNumber }, timestamp: ts });
          items.push({ kind: "stream", event: { type: "text_delta", text: textOf(d.content) }, timestamp: ts });
          items.push({
            kind: "stream",
            event: { type: "assistant_message", message: { role: "assistant", content: d.content as string | ContentBlock[] } },
            timestamp: ts,
          });
        }
        break;
      }
      case "tool_use": {
        items.push({
          kind: "stream",
          event: {
            type: "tool_use_start",
            toolCall: {
              id: String(d.toolCallId ?? ""),
              toolName: String(d.toolName ?? ""),
              args: (d.args ?? {}) as Record<string, unknown>,
            },
          },
          timestamp: ts,
        });
        // A TodoWrite call carries the canonical todo snapshot in its args. The
        // engine only re-emits it as a task_update inside run() (i.e. on the
        // NEXT send), so a plain session reopen / disk rebuild would otherwise
        // show an empty task panel even though the todos are right here. Mirror
        // the live tool: also emit a synthetic task_update so the pinned panel
        // re-hydrates from disk. (Same conversion as core's task.ts —
        // parse → position-based ids → "all done ⇒ clear".)
        if (String(d.toolName ?? "") === "TodoWrite") {
          const tasks = todosToTasks((d.args ?? {}) as Record<string, unknown>);
          if (tasks) {
            items.push({ kind: "stream", event: { type: "task_update", tasks }, timestamp: ts });
          }
        }
        break;
      }
      case "tool_result":
        items.push({
          kind: "stream",
          event: {
            type: "tool_result",
            result: {
              id: String(d.toolCallId ?? ""),
              toolName: String(d.toolName ?? ""),
              result: d.result as string | undefined,
              error: d.error as string | undefined,
              isError: d.isError as boolean | undefined,
            },
          },
          timestamp: ts,
        });
        break;
      case "subagent": {
        // Sub-agent spawn anchor → rebuild its card. We emit agent_start here
        // (sync, from the anchor); the async getSessionTranscript post-pass
        // reads sessions/<agentId>/ for status + result and appends the
        // matching agent_end / agent_backgrounded. agentId === childSid.
        const agentId = String(d.agentId ?? "");
        if (agentId) {
          items.push({
            kind: "stream",
            event: {
              type: "agent_start",
              agentId,
              ...(typeof d.name === "string" ? { name: d.name } : {}),
              description: String(d.description ?? ""),
            },
            timestamp: ts,
          });
        }
        break;
      }
      case "external_file_changes": {
        const changedFiles = Array.isArray(d.changedFiles)
          ? d.changedFiles.filter(
              (file): file is string => typeof file === "string" && file.length > 0,
            )
          : [];
        const cwd = typeof d.cwd === "string" ? d.cwd : "";
        if (changedFiles.length === 0 || !cwd) break;
        const status = d.status === "failed" ? "failed" : "completed";
        items.push({
          kind: "stream",
          event: {
            type: "background_agent_completed",
            agentId: String(d.jobId ?? "external-file-changes"),
            description: String(d.description ?? "DriveAgent file changes"),
            status,
            workKind: "cc",
            changedFiles,
            cwd,
            ...(typeof d.originClientMessageId === "string"
              ? { originClientMessageId: d.originClientMessageId }
              : {}),
            enqueuedAt: ts ?? 0,
          },
          timestamp: ts,
        });
        break;
      }
      case "turn_boundary":
        items.push({ kind: "stream", event: { type: "turn_complete", reason: "completed" }, timestamp: ts });
        break;
      case "summary":
        items.push({ kind: "stream", event: { type: "context_compact", strategy: "summary", before: 0, after: 0 }, timestamp: ts });
        break;
      case "error":
        items.push({ kind: "stream", event: { type: "error", error: String(d.error ?? "error") }, timestamp: ts });
        break;
      case "turn_stopped":
        // User interrupted this turn — rebuild the renderer's stop marker so
        // the interrupted turn renders flat (not folded). No elapsed on replay
        // (the in-memory live one had it; the marker alone keeps it unfolded).
        items.push({ kind: "turn_stopped", timestamp: ts });
        break;
      case "goal_progress":
        items.push({
          kind: "stream",
          event: {
            type: "goal_progress",
            status: (d.status as "not_met" | "met" | "exhausted") ?? "not_met",
            // A corrupt/hand-edited transcript may carry a non-numeric `round`;
            // Number("abc") === NaN would propagate invalid state. Fall back to 0.
            round: Number.isFinite(Number(d.round)) ? Number(d.round) : 0,
            ...(typeof d.gaps === "string" ? { gaps: d.gaps } : {}),
          },
          timestamp: ts,
        });
        break;
      // session lifecycle events with no renderer representation are ignored.
    }
  }
  // Close the final turn if its content (the trailing summary message and any
  // late tools) arrived after the last turn_boundary. Without this the last
  // turn never gets a turn_complete, so its files_changed card stays pinned
  // before the closing summary text instead of at the turn's end.
  if (sawBoundary && pendingContentAfterBoundary) {
    items.push({ kind: "stream", event: { type: "turn_complete", reason: "completed" }, timestamp: lastTs });
  }
  return items;
}

/**
 * Read + convert the transcript for `sessionId`. `baseDir` overridable for
 * tests; defaults to core's CODE_SHELL_HOME-aware sessions root. Returns []
 * when absent/empty.
 */
const SAFE_ID = /^[A-Za-z0-9_.-]+$/;

export async function getSessionTranscript(
  sessionId: string,
  baseDir: string = sessionsRoot(),
): Promise<FoldItem[]> {
  if (!SAFE_ID.test(sessionId) || sessionId === "." || sessionId === "..") return [];
  const file = path.join(baseDir, sessionId, "transcript.jsonl");
  try {
    const jsonl = await fs.readFile(file, "utf8");
    const items = transcriptToFoldItems(jsonl);
    return await enrichSubagentCards(items, baseDir);
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code === "ENOENT") return [];
    throw e;
  }
}

/** Statuses that mean the sub-agent finished/ended (terminal). Anything else
 *  (stuck "active") means it never wrapped up → render as interrupted. */
const SUBAGENT_DONE_STATUSES = new Set(["completed", "failed", "cancelled", "model_error", "aborted_streaming"]);

/**
 * Expand each replayed sub-agent `agent_start` (from a "subagent" anchor) into a
 * full card by reading the sub-agent's own session (sessions/<agentId>/):
 *   - its final output  = last assistant message in its transcript → text_delta
 *   - terminal status   → agent_end (done) — completed shows ✓, others ✗
 *   - stuck "active"     → agent_end{error:"中断"} so the card reads interrupted,
 *                          not a forever-spinning "running"
 * agentId === the sub-agent's session id (agent_id===childSid). Best-effort: a
 * missing/unreadable sub-agent session just leaves the bare agent_start (card
 * shows running) rather than failing the whole transcript.
 */
async function enrichSubagentCards(items: FoldItem[], baseDir: string): Promise<FoldItem[]> {
  const out: FoldItem[] = [];
  for (const item of items) {
    out.push(item);
    if (item.kind !== "stream" || item.event.type !== "agent_start") continue;
    const agentId = item.event.agentId;
    if (!agentId || !SAFE_ID.test(agentId)) continue;

    let status = "active";
    let resultText = "";
    try {
      const state = JSON.parse(
        await fs.readFile(path.join(baseDir, agentId, "state.json"), "utf8"),
      ) as { status?: string };
      status = typeof state.status === "string" ? state.status : "active";
    } catch {
      continue; // no sub-agent session on disk → leave bare agent_start
    }
    try {
      const subJsonl = await fs.readFile(path.join(baseDir, agentId, "transcript.jsonl"), "utf8");
      // Last assistant message in the sub-agent's own transcript = its output.
      for (const raw of subJsonl.split("\n")) {
        const line = raw.trim();
        if (!line) continue;
        let ev: TranscriptEvent;
        try { ev = JSON.parse(line) as TranscriptEvent; } catch { continue; }
        if (ev.type === "message" && (ev.data as { role?: string })?.role === "assistant") {
          resultText = textOf((ev.data as { content?: unknown }).content);
        }
      }
    } catch {
      /* no transcript → empty result, still mark terminal/interrupted below */
    }

    const ts = item.timestamp;
    if (resultText) {
      out.push({ kind: "stream", event: { type: "text_delta", text: resultText, agentId }, timestamp: ts });
    }
    if (SUBAGENT_DONE_STATUSES.has(status)) {
      out.push({
        kind: "stream",
        event: { type: "agent_end", agentId, description: item.event.description, text: resultText || undefined },
        timestamp: ts,
      });
    } else {
      // Stuck "active" — never wrapped up → interrupted. agent_end{error} so the
      // card resolves to a failed/interrupted state, not an eternal spinner.
      out.push({
        kind: "stream",
        event: { type: "agent_end", agentId, description: item.event.description, error: "上次会话中断,未完成" },
        timestamp: ts,
      });
    }
  }
  return out;
}
