import {
  Activity,
  AlarmClock,
  Archive,
  BarChart3,
  Bell,
  BookOpen,
  Bot,
  Box,
  Brain,
  Bug,
  Calendar,
  Camera,
  CheckCircle2,
  ClipboardList,
  Clock,
  Cloud,
  Code2,
  Compass,
  Cpu,
  Database,
  Download,
  FileText,
  Filter,
  Flag,
  Flame,
  FolderTree,
  Gauge,
  GitBranch,
  GitCompare,
  Globe,
  GraduationCap,
  Hammer,
  HardDrive,
  Heart,
  History,
  Home,
  Image,
  Inbox,
  KeyRound,
  Layers,
  LayoutDashboard,
  Library,
  Lightbulb,
  LineChart,
  Link,
  ListChecks,
  Lock,
  Mail,
  Map,
  MessageSquare,
  Mic,
  Monitor,
  Moon,
  Music,
  Newspaper,
  Package,
  Palette,
  PanelTop,
  PieChart,
  Plug,
  Puzzle,
  Radar,
  Rocket,
  Search,
  ServerCog,
  Settings,
  Shield,
  ShoppingCart,
  Sparkles,
  SquareTerminal,
  Star,
  Table2,
  Tag,
  Target,
  Terminal,
  Timer,
  TrendingUp,
  Trophy,
  UsersRound,
  Wallet,
  Wand2,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { PluginPanelIconName } from "../../shared/plugin-panels";

/** Explicit static allowlist map — no dynamic lucide imports (bundle safety). */
const PLUGIN_PANEL_ICON_MAP = {
  // v1 semantic aliases
  panel: PanelTop,
  chart: BarChart3,
  table: Table2,
  // lucide names
  activity: Activity,
  "alarm-clock": AlarmClock,
  archive: Archive,
  "bar-chart-3": BarChart3,
  bell: Bell,
  "book-open": BookOpen,
  bot: Bot,
  box: Box,
  brain: Brain,
  bug: Bug,
  calendar: Calendar,
  camera: Camera,
  "check-circle-2": CheckCircle2,
  "clipboard-list": ClipboardList,
  clock: Clock,
  cloud: Cloud,
  "code-2": Code2,
  compass: Compass,
  cpu: Cpu,
  database: Database,
  download: Download,
  "file-text": FileText,
  filter: Filter,
  flag: Flag,
  flame: Flame,
  "folder-tree": FolderTree,
  gauge: Gauge,
  "git-branch": GitBranch,
  "git-compare": GitCompare,
  globe: Globe,
  "graduation-cap": GraduationCap,
  hammer: Hammer,
  "hard-drive": HardDrive,
  heart: Heart,
  history: History,
  home: Home,
  image: Image,
  inbox: Inbox,
  "key-round": KeyRound,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  library: Library,
  lightbulb: Lightbulb,
  "line-chart": LineChart,
  link: Link,
  "list-checks": ListChecks,
  lock: Lock,
  mail: Mail,
  map: Map,
  "message-square": MessageSquare,
  mic: Mic,
  monitor: Monitor,
  moon: Moon,
  music: Music,
  newspaper: Newspaper,
  package: Package,
  palette: Palette,
  "panel-top": PanelTop,
  "pie-chart": PieChart,
  plug: Plug,
  puzzle: Puzzle,
  radar: Radar,
  rocket: Rocket,
  search: Search,
  "server-cog": ServerCog,
  settings: Settings,
  shield: Shield,
  "shopping-cart": ShoppingCart,
  sparkles: Sparkles,
  "square-terminal": SquareTerminal,
  star: Star,
  "table-2": Table2,
  tag: Tag,
  target: Target,
  terminal: Terminal,
  timer: Timer,
  "trending-up": TrendingUp,
  trophy: Trophy,
  "users-round": UsersRound,
  wallet: Wallet,
  "wand-2": Wand2,
  wifi: Wifi,
  wrench: Wrench,
  zap: Zap,
} as const satisfies Record<PluginPanelIconName, LucideIcon>;

/** Descriptors are validated upstream (core zod), but stale/foreign values degrade gracefully. */
export function resolvePluginPanelIcon(name: string): LucideIcon {
  return (PLUGIN_PANEL_ICON_MAP as Record<string, LucideIcon>)[name] ?? PanelTop;
}
