/**
 * Core message types for the CodeShell application.
 *
 * These types define the shape of all messages flowing through the system:
 * user input, assistant responses, system notifications, tool progress,
 * attachments, and streaming events.
 *
 * Generated by reverse-engineering usage across 150+ consumer files.
 */

import type { APIError } from '@anthropic-ai/sdk'
import type {
  BetaContentBlock,
  BetaMessage,
  BetaRawMessageStreamEvent,
} from '@anthropic-ai/sdk/resources/beta/messages/messages.mjs'
import type { ContentBlockParam } from '@anthropic-ai/sdk/resources/index.mjs'
import type { UUID } from 'crypto'
import type { Attachment } from '../utils/attachments.js'
import type { PermissionMode } from './permissions.js'
import type { BranchAction, CommitKind, PrAction } from '../tools/shared/gitOperationTracking.js'

/**
 * SDK assistant message error type. Matches the Zod enum in
 * entrypoints/sdk/coreSchemas.ts (SDKAssistantMessageErrorSchema).
 * Defined inline to avoid depending on generated types.
 */
export type SDKAssistantMessageError =
  | 'authentication_failed'
  | 'billing_error'
  | 'rate_limit'
  | 'invalid_request'
  | 'server_error'
  | 'unknown'
  | 'max_output_tokens'

/**
 * Base progress type for tool execution updates.
 * Tools extend this with their own progress data shapes.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Progress = Record<string, any>

// ============================================================================
// Shared / utility types
// ============================================================================

export type SystemMessageLevel = 'info' | 'warning' | 'error'

export type PartialCompactDirection = 'from' | 'up_to'

/**
 * Provenance of a user message. undefined = human (keyboard).
 */
export type MessageOrigin =
  | { kind: 'human' }
  | { kind: 'task-notification' }
  | { kind: 'coordinator' }
  | { kind: 'channel'; server: string }

/**
 * Information about a single hook execution, used in stop hook summaries
 * and collapsed read/search groups.
 */
export type StopHookInfo = {
  command: string
  promptText?: string
  durationMs?: number
}

// ============================================================================
// Core message types
// ============================================================================

/**
 * A message from the user (human input, tool results, meta messages).
 */
export type UserMessage = {
  type: 'user'
  uuid: UUID
  timestamp: string
  message: {
    role: 'user'
    content: string | ContentBlockParam[]
  }
  isMeta?: true
  isVisibleInTranscriptOnly?: true
  isVirtual?: true
  isCompactSummary?: true
  summarizeMetadata?: {
    messagesSummarized: number
    userContext?: string
    direction?: PartialCompactDirection
  }
  toolUseResult?: unknown
  /** MCP protocol metadata (never sent to model) */
  mcpMeta?: {
    _meta?: Record<string, unknown>
    structuredContent?: Record<string, unknown>
  }
  imagePasteIds?: number[]
  /** UUID of the assistant message containing the matching tool_use */
  sourceToolAssistantUUID?: UUID
  /** Permission mode when message was sent (for rewind restoration) */
  permissionMode?: PermissionMode
  origin?: MessageOrigin
}

/**
 * A message from the assistant (API response).
 * Wraps the Anthropic SDK's BetaMessage type with additional metadata.
 */
export type AssistantMessage = {
  type: 'assistant'
  uuid: UUID
  timestamp: string
  message: BetaMessage
  requestId: string | undefined
  isMeta?: true
  isVirtual?: true
  isApiErrorMessage?: boolean
  apiError?: string
  error?: SDKAssistantMessageError
  errorDetails?: string
  advisorModel?: string
}

/**
 * A progress update from a tool execution.
 */
export type ProgressMessage<P extends Progress = Progress> = {
  type: 'progress'
  uuid: UUID
  timestamp: string
  data: P
  toolUseID: string
  parentToolUseID: string
}

/**
 * An attachment message (hook results, file attachments, etc.).
 */
export type AttachmentMessage<A extends Attachment = Attachment> = {
  type: 'attachment'
  uuid: UUID
  timestamp: string
  attachment: A
}

/**
 * Hook result messages are attachment messages produced by hook execution.
 */
export type HookResultMessage = AttachmentMessage

// ============================================================================
// System message variants
// ============================================================================

export type SystemInformationalMessage = {
  type: 'system'
  subtype: 'informational'
  content: string
  level: SystemMessageLevel
  uuid: UUID
  timestamp: string
  isMeta?: boolean
  toolUseID?: string
  preventContinuation?: boolean
}

export type SystemAPIErrorMessage = {
  type: 'system'
  subtype: 'api_error'
  level: 'error'
  cause?: Error
  error: APIError
  retryInMs: number
  retryAttempt: number
  maxRetries: number
  uuid: UUID
  timestamp: string
}

export type SystemLocalCommandMessage = {
  type: 'system'
  subtype: 'local_command'
  content: string
  level: SystemMessageLevel
  uuid: UUID
  timestamp: string
  isMeta?: boolean
}

export type SystemPermissionRetryMessage = {
  type: 'system'
  subtype: 'permission_retry'
  content: string
  commands: string[]
  level: SystemMessageLevel
  uuid: UUID
  timestamp: string
  isMeta?: boolean
}

export type SystemBridgeStatusMessage = {
  type: 'system'
  subtype: 'bridge_status'
  content: string
  url: string
  upgradeNudge?: string
  uuid: UUID
  timestamp: string
  isMeta?: boolean
}

export type SystemScheduledTaskFireMessage = {
  type: 'system'
  subtype: 'scheduled_task_fire'
  content: string
  uuid: UUID
  timestamp: string
  isMeta?: boolean
}

export type SystemStopHookSummaryMessage = {
  type: 'system'
  subtype: 'stop_hook_summary'
  hookCount: number
  hookInfos: StopHookInfo[]
  hookErrors: string[]
  preventedContinuation: boolean
  stopReason: string | undefined
  hasOutput: boolean
  level: SystemMessageLevel
  uuid: UUID
  timestamp: string
  toolUseID?: string
  hookLabel?: string
  totalDurationMs?: number
}

export type SystemTurnDurationMessage = {
  type: 'system'
  subtype: 'turn_duration'
  durationMs: number
  budgetTokens?: number
  budgetLimit?: number
  budgetNudges?: number
  messageCount?: number
  uuid: UUID
  timestamp: string
  isMeta?: boolean
}

export type SystemAwaySummaryMessage = {
  type: 'system'
  subtype: 'away_summary'
  content: string
  uuid: UUID
  timestamp: string
  isMeta?: boolean
}

export type SystemMemorySavedMessage = {
  type: 'system'
  subtype: 'memory_saved'
  writtenPaths: string[]
  uuid: UUID
  timestamp: string
  isMeta?: boolean
}

export type SystemAgentsKilledMessage = {
  type: 'system'
  subtype: 'agents_killed'
  uuid: UUID
  timestamp: string
  isMeta?: boolean
}

export type SystemApiMetricsMessage = {
  type: 'system'
  subtype: 'api_metrics'
  ttftMs: number
  otps: number
  isP50?: boolean
  hookDurationMs?: number
  turnDurationMs?: number
  toolDurationMs?: number
  classifierDurationMs?: number
  toolCount?: number
  hookCount?: number
  classifierCount?: number
  configWriteCount?: number
  uuid: UUID
  timestamp: string
  isMeta?: boolean
}

export type SystemCompactBoundaryMessage = {
  type: 'system'
  subtype: 'compact_boundary'
  content: string
  level: SystemMessageLevel
  uuid: UUID
  timestamp: string
  isMeta?: boolean
  compactMetadata: {
    trigger: 'manual' | 'auto'
    preTokens: number
    userContext?: string
    messagesSummarized?: number
  }
  logicalParentUuid?: UUID
}

export type SystemMicrocompactBoundaryMessage = {
  type: 'system'
  subtype: 'microcompact_boundary'
  content: string
  level: SystemMessageLevel
  uuid: UUID
  timestamp: string
  isMeta?: boolean
  microcompactMetadata: {
    trigger: 'auto'
    preTokens: number
    tokensSaved: number
    compactedToolIds: string[]
    clearedAttachmentUUIDs: string[]
  }
}

/**
 * Union of all system message variants.
 */
export type SystemMessage =
  | SystemInformationalMessage
  | SystemAPIErrorMessage
  | SystemLocalCommandMessage
  | SystemPermissionRetryMessage
  | SystemBridgeStatusMessage
  | SystemScheduledTaskFireMessage
  | SystemStopHookSummaryMessage
  | SystemTurnDurationMessage
  | SystemAwaySummaryMessage
  | SystemMemorySavedMessage
  | SystemAgentsKilledMessage
  | SystemApiMetricsMessage
  | SystemCompactBoundaryMessage
  | SystemMicrocompactBoundaryMessage

// ============================================================================
// Top-level message union
// ============================================================================

/**
 * Union of all message types that flow through the system.
 */
export type Message =
  | UserMessage
  | AssistantMessage
  | ProgressMessage
  | AttachmentMessage
  | SystemMessage

// ============================================================================
// Normalized message types (single content block per message)
// ============================================================================

/**
 * An assistant message normalized to have exactly one content block.
 */
export type NormalizedAssistantMessage = Omit<AssistantMessage, 'message'> & {
  type: 'assistant'
  message: Omit<BetaMessage, 'content'> & {
    content: [BetaContentBlock]
    context_management: BetaMessage['context_management']
  }
}

/**
 * A user message normalized to have content as a single-element array.
 */
export type NormalizedUserMessage = Omit<UserMessage, 'message'> & {
  type: 'user'
  message: {
    role: 'user'
    content: [ContentBlockParam]
  }
}

/**
 * Union of all normalized message types.
 */
export type NormalizedMessage =
  | NormalizedAssistantMessage
  | NormalizedUserMessage
  | AttachmentMessage
  | SystemMessage
  | ProgressMessage

// ============================================================================
// Streaming & request event types
// ============================================================================

/**
 * A streaming event wrapping the Anthropic SDK's raw message stream event.
 */
export type StreamEvent = {
  type: 'stream_event'
  event: BetaRawMessageStreamEvent
  /** Time to first token in milliseconds (present on message_start events) */
  ttftMs?: number
}

/**
 * Emitted when a new API request starts (before streaming begins).
 */
export type RequestStartEvent = {
  type: 'stream_request_start'
}

// ============================================================================
// Special message types
// ============================================================================

/**
 * A tombstone message signals that a previously emitted message should
 * be removed from the message list (used during streaming cleanup).
 */
export type TombstoneMessage = {
  type: 'tombstone'
  message: Message
}

/**
 * A tool use summary message provides human-readable progress updates
 * after tool batches complete. SDK-only (not rendered in REPL).
 */
export type ToolUseSummaryMessage = {
  type: 'tool_use_summary'
  summary: string
  precedingToolUseIds: string[]
  uuid: UUID
  timestamp: string
}

// ============================================================================
// Collapsed read/search group (UI rendering)
// ============================================================================

/**
 * A message that can be collapsed into a read/search group.
 * This is a subtype of NormalizedAssistantMessage or NormalizedUserMessage
 * that represents a collapsible tool use or tool result.
 */
export type CollapsibleMessage = NormalizedAssistantMessage | NormalizedUserMessage

/**
 * A collapsed group of consecutive read/search operations for compact UI display.
 */
export type CollapsedReadSearchGroup = {
  type: 'collapsed_read_search'
  uuid: UUID
  timestamp: string
  searchCount: number
  readCount: number
  listCount: number
  replCount: number
  memorySearchCount: number
  memoryReadCount: number
  memoryWriteCount: number
  readFilePaths: string[]
  searchArgs: string[]
  latestDisplayHint?: string
  messages: CollapsibleMessage[]
  displayMessage: CollapsibleMessage
  // Optional counts for specific operation types
  mcpCallCount?: number
  mcpServerNames?: string[]
  bashCount?: number
  gitOpBashCount?: number
  // Git operation tracking
  commits?: CommitKind[]
  pushes?: string[]
  branches?: BranchAction[]
  prs?: PrAction[]
  // Hook tracking within collapsed groups
  hookCount?: number
  hookTotalMs?: number
  hookInfos?: StopHookInfo[]
  // Team memory operations (feature-gated)
  teamMemorySearchCount?: number
  teamMemoryReadCount?: number
  teamMemoryWriteCount?: number
  // Relevant memories absorbed from attachments
  relevantMemories?: Attachment[]
}

/**
 * Union type for all messages that can be rendered in the UI message list.
 * Includes normalized messages plus collapsed read/search groups.
 */
export type RenderableMessage =
  | NormalizedAssistantMessage
  | NormalizedUserMessage
  | AttachmentMessage
  | SystemMessage
  | CollapsedReadSearchGroup
